### ISSUE TITLE
Bug: `repeat last command` does not ignore automatically run commands

### ISSUE THREAD

**Issue by chrisgrieser** [1C0D/obsidian-repeat-last-commands#2]
Thanks for the small, nice plugin.

So the issue I have is that I use the linter plugin, which has a feature to "add" a command to its linting process:
![Pasted image 2024-01-12 at 14 53 11@2x](https://github.com/1C0D/obsidian-repeat-last-commands/assets/73286100/ba241028-359e-4134-bcd3-de255dc5b2d1)

And it appears that `repeat last command` in fact picks up on *every* command last run, including the ones automatically run by the linter. 

Another issue are commands ran via the [advanced-uri-plugin](https://vinzent03.github.io/obsidian-advanced-uri/actions/commands). These also often happen automatically, and also take place of the last-run command.

And the final case I noticed is that commands run via hotkey, too, get treated as last command. So every time I do `cmd+b` to bold a selection, that gets saved as last command.

All these cases somewhat defeat the purpose of the plugin: the plugin is most useful when you want temporarily quick access to a command. However, automated commands and hotkey commands "take over" the spot of the last repeated command, even though you do not need access to them (as you already have a hotkey / automation to run them).

---

I am not sure how feasible that would be, but what I'd propose is to add an option to only remember commands when they are run from the command palette.

**Comment by 1C0D** [comment]
I have to sleep, to read this clearly. But to the first question I can answer: there is a function getRejectedCondition to reject commands generated by RLC. But I could extend this with an opened setting in a text area. With the condition if command startswith don't repeat this command. There is a command to copy command's ids. So pasting the id in the text area, it will be possible to block the command. Or all commands  from a plugin if just pasting Linter: ...

**Comment by 1C0D** [comment]
well done maybe not what you were asking but in version 2.1.0 you can exclude some commands from last command(s) or even the whole plugin e.g: 
![image](https://github.com/1C0D/obsidian-repeat-last-commands/assets/63018905/c5a3bdf0-985b-4302-9cee-cb6186025d20)

**Comment by 1C0D** [comment]
Ok, I read in Z, I think this last release is fixing your problems. Don't hesitate to add more comments.
