### ISSUE TITLE
[Feature Request] CSS: Repeat Commands MODAL -> Expose Plugin Name for Specific Style

### ISSUE THREAD

**Issue by FelipeRearden** [1C0D/obsidian-repeat-last-commands#7]
Hello @1C0D !!!!

If possible would you mind exposing the name of the plugin inside `Repeat Command(s) MODAL ` in a specific div?

Example: in the `.suggestion-item div` has  `PLUGIN NAME:` `COMMAND NAME`

- I wanna target only `PLUGIN NAME:`

I am asking you about this because I wanna apply a different style to this part of the suggestion-item.

- In my case I wanna `display: none` 

<hr> 

Let me know if you need more information!

Have a great day !!!!

**Comment by 1C0D** [comment]
version 2.6.0:
settings option: show command id in repeat last commands modal.
and there is a class .id-suggest in the css

**Comment by 1C0D** [comment]
I was really not sure about this plugin, but it seems to become useful

**Comment by FelipeRearden** [comment]
> settings option: show command id in repeat last commands modal.

Thank for the new feature :) I was using a custom css to hide the command id and this is much better :)

> I'm not sure to understand. what do you want to hide the id (second line) ? because the name first line, it's not really possible. But I guess you meant the id. I can add an option to not show the id.

No. It is not about the second line. It is about a **subset** of the first line for commands from the community plugins.

Let use an example: the Templater plugin has a command in the Command Palette called `Templater: Insert from Template Modal`

This command has two parts:
1- The `PLUGIN NAME:` Templater:
2- The `COMMAND NAME` Insert from Template Modal 

My FR is a css changes that let me style only the `Templater:` instead of `Templater: Insert from Template Modal`
 
Some users will change the color of `Templater:` . In my case I wanna apply display: none

<hr>

Let me know if something is not clear :)

**Comment by 1C0D** [comment]
But if you don't show the plugin name, some commands may have the same command name. And you can't distinguish obsidian commands from plugins commands. It's difficult to add a setting for this for everybody. And to add a class only I need to add some weird code breaking the logic and maybe slowing things down. I let this opened for the moment, but after a look on how to do it, I'm really inspired on this.

**Comment by FelipeRearden** [comment]
> It's difficult to add a setting for this for everybody. And to add a class only, I need to add some weird code breaking the logic and maybe slowing things down.
Anyway, It's not doable. 

100% understood @1C0D ! It is okay :)

In my user mind it was a simple feature to add and thank you for let me know that is not doable :)

Feel free to close this issue :)
I wish you a fantastic day ☀️

**Comment by 1C0D** [comment]
Finally I did it. I will comment css

**Comment by 1C0D** [comment]
lol
![image](https://github.com/1C0D/obsidian-repeat-last-commands/assets/63018905/63a2fe7d-6a79-4dfd-87da-d816b48c6b7e)

**Comment by FelipeRearden** [comment]
> lol ![image](https://private-user-images.githubusercontent.com/63018905/304852344-63a2fe7d-6a79-4dfd-87da-d816b48c6b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Mzk1MzgsIm5iZiI6MTcwNzkzOTIzOCwicGF0aCI6Ii82MzAxODkwNS8zMDQ4NTIzNDQtNjNhMmZlN2QtNmE3OS00ZGZkLTg3ZGEtZDgxNmI0OGM2YjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE5MzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOWVlYTkxMTYyYjY5OTUwMGVjNmMwZTVmYjdlYWVhMDI0MmZiMjdjOTg3ZjE0NThlMzlkZDE1YTQyMmI5NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_tSs7ynwErrRSdmA-oDq_PIBszp7smCFrWsKgZM7LE)

🎉 🎉 🎉 🎉

CSS is a crazy. We never know what is gonna happen :)

**Comment by 1C0D** [comment]
like this is seems better
![image](https://github.com/1C0D/obsidian-repeat-last-commands/assets/63018905/3bc86279-1022-41af-956a-412940cf295c)

**Comment by FelipeRearden** [comment]
> like this it seems better
> 
> ![image](https://github.com/1C0D/obsidian-repeat-last-commands/assets/63018905/3bc86279-1022-41af-956a-412940cf295c)
> 
> 
> 
> 

Looks very good to me too :)

**Comment by 1C0D** [comment]
version 2.7.0
Done. It seems a very good idea to distinguish obsidian commands. color obsidian
and you can customize the first added class as you wanted

**Comment by FelipeRearden** [comment]
> version 2.7.0 Done. It seems a very good idea to distinguish obsidian commands. color obsidian and you can customize the first added class as you wanted

Amazing, amazing, amazing !!!!

Working perfect on version `2.7.0` !!!

Thank you very much for the hard work for making this real 🙏

**Comment by 1C0D** [comment]
You are welcome
