### ISSUE TITLE
Bug: Navigating the command palette by keyboard is not possible with plugin enabled

### ISSUE THREAD

**Issue by brosell** [1C0D/obsidian-repeat-last-commands#8]
Steps to reproduce:
- enable the plugin with default settings
- ctrl-p o open the palette
- use the down cursor key to move the highlight

Expected behavior: You are able to scroll through the list. If you pause on an entry the highlight remains on the entry until selected or more navigating the list.

Observed behavior: After a brief pause the highlight jumps back to the first command in the list.

**Comment by 1C0D** [comment]
version 2.2.6 
ok fixed

**Comment by brosell** [comment]
Verified
